networks:
  cloud-net:
    name: cloud-net

services:

  web-frontend-server:
    build: ./web-frontend-server
    image: nguyennhathao/web:dev
    container_name: web-frontend-server
    networks: [cloud-net]
    dns: 
      - 172.18.0.9
    ports: ["8080:80"]

  application-backend-server:
    build: ./application-backend-server
    image: nguyennhathao/app:dev
    container_name: application-backend-server
    networks: [cloud-net]
    dns:
      - 172.18.0.9
    ports: ["8085:8081"]
    environment:
      OIDC_ISSUER: "http://authentication-identity-server:8080/realms/realm_sv52300198"
      OIDC_AUDIENCE: "account"

  relational-database-server:
    image: mariadb:11
    container_name: relational-database-server
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: minicloud
    volumes:
      - ./relational-database-server/init:/docker-entrypoint-initdb.d:ro
    networks: [cloud-net]
    dns:
      - 172.18.0.9
    ports: ["3306:3306"]

  authentication-identity-server:
    image: quay.io/keycloak/keycloak:latest
    container_name: authentication-identity-server
    command: ["start-dev"]
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HOSTNAME: "localhost"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
    ports: ["8081:8080"]
    restart: unless-stopped
    networks: [cloud-net]
    dns:
      - 172.18.0.9
    volumes:
      - ./authentication-identity-server/data:/opt/keycloak/data

  object-storage-server:
    image: minio/minio
    container_name: object-storage-server
    command: ["server","/data","--console-address",":9001"]
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./object-storage-server/data:/data
    networks: [cloud-net]
    dns:
      - 172.18.0.9
    ports: ["9000:9000", "9001:9001"]

  internal-dns-server:
    image: internetsystemsconsortium/bind9:9.18
    container_name: internal-dns-server
    ports: ["1053:53/udp"]
    volumes:
      - ./internal-dns-server/named.conf:/etc/bind/named.conf:ro
      - ./internal-dns-server/named.conf.options:/etc/bind/named.conf.options:ro
      - ./internal-dns-server/named.conf.local:/etc/bind/named.conf.local:ro
      - ./internal-dns-server/db.cloud.local:/etc/bind/db.cloud.local:ro
    networks: [cloud-net]
    dns:
      - 172.18.0.9

  monitoring-node-exporter-server:
    image: prom/node-exporter:latest
    container_name: monitoring-node-exporter-server
    networks: [cloud-net]
    dns:
      - 172.18.0.9
    ports: ["9100:9100"]

  monitoring-prometheus-server:
    image: prom/prometheus:latest
    container_name: monitoring-prometheus-server
    volumes:
      - ./monitoring-prometheus-server/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks: [cloud-net]
    dns:
      - 172.18.0.9
    ports: ["9090:9090"]

  monitoring-grafana-dashboard-server:
    image: grafana/grafana:latest
    container_name: monitoring-grafana-dashboard-server
    networks: [cloud-net]
    dns:
      - 172.18.0.9
    ports: ["3000:3000"]

  api-gateway-proxy-server:
    image: nginx:stable
    container_name: api-gateway-proxy-server
    depends_on:
      - web-frontend-server
      - application-backend-server
      - authentication-identity-server
    networks: [cloud-net]
    dns:
      - 172.18.0.9
    ports: ["80:80"]
    volumes:
      - ./api-gateway-proxy-server/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
