global: { scrape_interval: 15s }
scrape_configs:
  - job_name: 'node'
    static_configs: [ { targets: ['monitoring-node-exporter-server:9100'] } ]
  # Mở rộng: giám sát web-frontend-server
  - job_name: 'web'
    static_configs:
      - targets: ['web-frontend-server:80']
